name 'synyx-elasticsearch'
version '0.2.0'
author 'Johannes Graf'
license 'MIT License'
project_page 'https://github.com/synyx/puppet-elasticsearch'
source 'https://github.com/synyx/puppet-elasticsearch.git'
summary 'Puppet module to install elasticsearch'
description 'A Puppet module to install elasticsearch'
dependency 'grafjo/openjdk7', '0.1.0'
dependency 'puppetlabs/stdlib', '>=0.0.1'
dependency 'puppetlabs/apt', '>=0.0.1'
