name 'synyx-elasticsearch'
version '0.1.1'
author 'Johannes Graf'
license 'MIT License'
project_page 'https://github.com/synyx/puppet-elasticsearch'
source 'https://github.com/synyx/puppet-elasticsearch.git'
summary 'Puppet module to install elasticsearch'
description 'A Puppet module to install elasticsearch'
dependency 'grafjo/openjdk7', '0.1.0'
dependency 'puppetlabs/stdlib', '3.x'
dependency 'puppetlabs/apt', '1.x'
